swagger: '2.0'
info:
  title: pet shop
  version: '1.0'
  description: Testing
  contact:
    name: Jonas
    email: jonas@example.com
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
tags:
  - name: foo
    description: Foo
  - name: test
    description: Test

paths:
  /foos:
    post:
      summary: create foo
      tags:
        - foo
        - test
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Foo'
      operationId: post-foos
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Foo'
          description: The foo to create
      description: |-
        Description here...

        - foo
        - bar
definitions:
  Foo:
    title: Foo
    type: object
    properties:
      id:
        type: string
      name:
        type: string
        format: email
      description:
        type: string
