swagger: '2.0'
info:
  title: pet shop
  version: '1.0'
  description: Testing
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /foos:
    post:
      summary: create foo
      tags:
        - foo
      responses: {}
      operationId: post-foos
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Foo'
          description: ''
definitions:
  Foo:
    title: Foo
    type: object
    properties:
      id:
        type: string
      name:
        type: string
        format: email
      description:
        type: string
